@header

:Des <a href="/cookies.html" target="_blank" rel="noopener noreferrer">cookies</a> sont utilisés sur ce site afin d'améliorer l'expérience utilisateur.

<hr>

:Texte :

<textarea class="big-text" rows="10" cols="50" id="text"></textarea>

<p>
	<button class="big-btn" onclick="convertText();">Ajouter des numéros de ligne</button>
	<button class="big-btn" onclick="resetText();">RESET</button>
</p>

<script src="./editeurs/keyboard.js"></script>
<script src="./editeurs/numlines.js"></script>

@end